name: mytheresa-test

services:

  nginx:
    container_name: mytheresa_test_nginx
    depends_on:
      - php-fpm
    image: nginx:stable-alpine
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php-fpm/public:/mytheresa-test/php-fpm/public
    networks:
      - mytheresa-test-network

  php-fpm:
    container_name: mytheresa_test_php-fpm
    depends_on:
      - postgres
    build:
      dockerfile: php-fpm/Dockerfile
      target: prod
    environment:
      APP_ENV: ${APP_ENV}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - mytheresa-test-network

  postgres:
    container_name: mytheresa_test_network
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${DB_PORT}
    volumes:
      - mytheresa-test-db:/var/lib/postgresql/data
    networks:
      - mytheresa-test-network

volumes:
  mytheresa-test-db:

networks:
  mytheresa-test-network:
