name: CI

# Code static analysis and linting

on:
  push:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.4.0

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install composer and dependencies
        run: composer install --no-interaction --no-progress
        working-directory: ./php-fpm

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover var/phpunit/clover.xml
        working-directory: ./php-fpm
        env:
          XDEBUG_MODE: coverage

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: var/phpunit/clover.xml
          verbose: true

  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.4.0

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install composer and dependencies
        run: composer install --no-interaction --no-progress
        working-directory: ./php-fpm

      - name: Run PHPStan checks
        run: vendor/bin/phpstan analyse --no-progress
        working-directory: ./php-fpm

  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.4.0

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install composer and dependencies
        run: composer install --no-interaction --no-progress
        working-directory: ./php-fpm

      - name: Run Laravel Pint
        run: vendor/bin/pint --test
        working-directory: ./php-fpm
