name: CI

# Code static analysis and linting

on:
  push:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.4.0

      - name: Install composer and dependencies
        uses: php-actions/composer@v6

      - name: Run PHPUnit
        uses: php-actions/phpunit@master # php-actions/phpunit@v3 fails
        env:
          XDEBUG_MODE: coverage
        with:
          version: composer
          php_version: 8.4
          php_extensions: xdebug
          configuration: phpunit.xml
          coverage_clover: var/phpunit/clover.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: var/phpunit/clover.xml
          verbose: true

  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.4.0

      - name: Install composer and dependencies
        uses: php-actions/composer@v6
        with:
          working_dir: ./php-fpm

      - name: Run PHPStan checks
        uses: php-actions/phpstan@v3
        with:
          version: composer
          php_version: 8.4
          configuration: ./php-fpm/phpstan.neon

  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.4.0

      - name: Install composer and dependencies
        uses: php-actions/composer@v6

      - name: Run Laravel Pint
        uses: sergotail/laravel-pint-action@v2.0.0
        with:
          useComposer: true
          testMode: true
          verboseMode: true
          configPath: ./php-fpm/pint.json
